### ISSUE TITLE
Error if micropython is not located in /usr/bin.

### ISSUE THREAD

**Issue by Glutexo** [encukou/t3#2]
FileNotFoundError is raised right upon launch if the `micropython` binary is not located in `/usr/bin/micropython`. However, `which micropython` returns a working path. The error looks like this:

```
FileNotFoundError: [Errno 2] No such file or directory: b'/usr/bin/micropython'
```

Using the full path instead of just `'micropython'` in the `os.execvpe` call fixes this, but that is rather not a desired way.

**Comment by encukou** [comment]
Fixed in 653ce91979d9e1fec5a60f412cf415ce4a343a66. Thanks for debugging this!
