### ISSUE TITLE
Emulator hangs on first frame

### ISSUE THREAD

**Issue by Glutexo** [encukou/t3#5]
When run without parameters, the emulator launches, its screen appears, but nothing happens. The initial animation does not run. When run using a game name as a parameter, only the first frame of the game appears, but nothing happens then. The emulator does not respond to button presses. No error is written to the console.

**Comment by Glutexo** [comment]
94a3a52 is the first broken revision.

**Comment by encukou** [comment]
Interesting. I assume this is on Mac OS.

Will you be at Pyvo on Thursday so I could look at the bug?

**Comment by Glutexo** [comment]
Sure, macOS 10.12.1, Python 3.5.2, Micropython 1.8.6, click 6.6, pyglet 1.2.4.

**Comment by encukou** [comment]
It was a new MicroPython version, fixed in 4428e218bea1b66c67a79ac591927131dd14dd8f
Thanks for your time at the debugging session! :)
