### ISSUE TITLE
wait_for_input gets confused on simultaneous presses

### ISSUE THREAD

**Issue by Glutexo** [encukou/t3#7]
When `t3.wait_for_input()` is used to capture input, the results get confused when more than one button is pressed at the same time. Then, upon a button press, different button presses/releases can be yielded.

Try this simple code:

```python 
def main():
    i = 0
    while True:
        print('------', i)
        result = yield t3.wait_for_input()
        print(result)
        i += 1
```

Hold one button, press many others while still holding the first one. Press a button – the result can be different from the actually pressed button code. This state persists over subsequent presses as well.

**Comment by encukou** [comment]
Thanks for the report!
